[package]
name = "reptr"
version = "0.1.0"
edition = "2021"

[dependencies]
dart-parser = { path = "../dart-parser" }
clap = { version = "4.3.19", features = ["cargo", "derive"] }
futures = "0.3.28"
tokio = { version = "1.32.0", features = ["full"] }
rayon = "1.7.0"
